{% set name = "lz4" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1431d84a9cfb23e6773e72078ce8e65cad6745816d4cbf9ae67da5ea419acda

build:
  ignore_run_exports:
    - lz4-c  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed .
  skip: True  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest-runner
    - setuptools_scm
    - pkgconfig
    - lz4-c
  run:
    - python
    - lz4-c
    - sphinx >=1.6.0
    - flake8

test:
  imports:
    - lz4
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-lz4/python-lz4
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: LZ4 Bindings for Python
  description: |
    Provides a Python interface for the LZ4 compression library.
    LZ4 library provides support for three specifications-
    frame format,block format and stream format.
  doc_url: http://python-lz4.readthedocs.io/en/stable/
  dev_url: https://github.com/python-lz4/python-lz4

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
