{% set name = "lz4" %}
{% set version = "4.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f0b9e53c1e82e88c10d7c180069363980136b9d7a8306c4dca4f760d60c39f0

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed .
  skip: true  # [py<39]

requirements:
  build:
    - {{ cstdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - toml
    - wheel
    - pkgconfig
    - lz4-c {{ lz4_c }}
  run:
    - python
    - lz4-c # bounds through run_exports

# https://github.com/python-lz4/python-lz4/blob/v4.4.5/setup.py#L146-L150
# lz4.stream is experimental, disabled by default
{% set ignore_tests = "--ignore=tests/stream" %}

test:
  source_files:
    - tests
  imports:
    - lz4
    - lz4.block
    - lz4.frame
  requires:
    - pip
    - pytest
    - psutil
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ ignore_tests }}

about:
  home: https://github.com/python-lz4/python-lz4
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: LZ4 Bindings for Python
  description: |
    Provides a Python interface for the LZ4 compression library.
    LZ4 library provides support for three specifications-
    frame format,block format and stream format.
  doc_url: https://python-lz4.readthedocs.io
  dev_url: https://github.com/python-lz4/python-lz4

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
