travis:
  secure:
    BINSTAR_TOKEN: RwpKNBTC+fkJqmn0tfIfQzI8VHBzYodtD42VeIMLLG5IAcpAC8epCfymHXR2UU/f70p2Lom/WgAU5XGiRi9BErlAZk0p15icKqS+p48sIC+/NWYI0ct+h0cx1ENrLb8TvRGTLiIwkeGatktocKoFd5nrCl/GvaIYU/PhdTVD9Goxm+jo8nu8A1yTNa7QyXCeQ+SXrWQT9lnynb98DkkpKiOb+xuqE0cNzr6OvPRzTpGm/0A5DJ8f87kgt9U4FFmQrrXg02bf6Tk1VA+IF8JRrpfD8wijB0VoimZYc0Sj3OWO5DLLo4glcvQ5oaJk6c0uJg60OAzKwo0wxDxvBi9D8wI8kYjskDarjdwMYeg4lqGxVAhF2IrvmxJ5qXu8XZDjeBK+FNifwxiSmiCPjd2IP8A4XS1Q6Hc/j23/ST6HMXa78aai1BNEoflyd4iTFKZ63YcJxMtXjwXyMduBrwFrzDvN6dbl6l1CC2BayRSx6FHWDqO1c+bCNBZT60z8Rw4hxD2/qxMq9x/Tod20guJ3ot5xXrzB6ybpPMM7d7Zs5UWkijNJTOnf81fVVPT8WywMzzCMg+L8jd3M7+hMJr80praIxZK76eMUt7NmWmeNdy+p83oi6yW9S1LcS9tC+hc1dTL0TayADv3d3fKQ7rAo/37M55MltTKvQ3RyhdNG3bw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
