travis:
  secure:
    BINSTAR_TOKEN: MEyXZAYbJf7W45eaSrEgSiPBSjP3zD5Ic7Z2eJy/zKa7Q+o5x4VHHdewNMC/8+LKvS6pLSpg1Eav+4Ehy7lTSWKVcVAKSetviAYQZ9E6Bu+c7I1+Xe9GnN8tvbLE0oLDH7DN8YMJ76ZAUwaq1RQjDdh7V29q3AKFDiaPU8JGvGFRgoKxMsuCFQGLVV8WHMInL10dgb30CzlZndbtG16zR2C5mEL1ppUBBsHJ3LSHPLvoLdlDpL0+gG15BWAeSC9Wor2G3RfSmNhkmqmF6MPUtM3q9raGZ157OSEyeWoO8GPrGAX+FSsMbHcZZiIgq5ONp5qe17OxfHFJfcYanFZAqVZwCsGtJT+kZYsRPA98XigtiYlcIpLTrKw+Q9gr2AlLHaZzEK1ocGSM84Am2JMNKgi4KLO4LdWQoUn97BFNZx6wSgVq4qqd3Dc/z2AnhyqduchH6aIkuXGvgO7CcWD0Eclwddiv0Sxtt48TK8Y7ci2/Nc47OfsjaZgoXcwCbxBOgKlr7LFNFTgH2Eb7p84OQdB97XK0gOmveohMs3qOOXWELpLdmqkfsgsIUwaIJvZPve4uZDCJ4nL3a00UEjSNYj8zL5tvhKlecAWrOp/lWN2YyWOnP6tRJ+1SsqcXwEeGkgJIcChHE01aDZ4YLHS8JBQqN2zvcoFdAbzfVTiypyw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
